import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  screenPad: { padding: 16, paddingBottom: 26 },
  hero: { borderWidth: 1, borderRadius: 16, padding: 16, marginBottom: 20 },
  heroTitle: { fontSize: 28, fontWeight: "800" },
  sectionTitle: { fontSize: 20, fontWeight: "700" },
  sectionSubtitle: { marginTop: 4, fontSize: 13 },
  screenTitle: { fontSize: 24, fontWeight: "800", marginBottom: 12 },
  card: { borderWidth: 1, borderRadius: 16, marginBottom: 14, overflow: "hidden" },
  cardImage: { width: "100%", height: 180 },
  cardBody: { padding: 12 },
  cardTitle: { fontSize: 17, fontWeight: "800" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 10 },
  actionBtn: { borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16 },
  actionBtnText: { color: "#111", fontWeight: "700" },
  iconBtn: { borderWidth: 1, borderRadius: 10, width: 38, height: 38, alignItems: "center", justifyContent: "center" },
  badge: {
    position: "absolute",
    left: 10,
    top: 10,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  badgeText: { color: "#e4e4e7", fontSize: 10, fontWeight: "700", textTransform: "uppercase" },
  searchWrap: {
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  searchInput: { flex: 1, paddingVertical: 10, paddingHorizontal: 8 },
  switchRow: { flexDirection: "row", alignItems: "center" },
  emptyWrap: {
    margin: 16,
    borderWidth: 1,
    borderRadius: 16,
    padding: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  stat: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginRight: 8,
    marginBottom: 10,
  },
  singleInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  listRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  thumb: { width: 64, height: 64, borderRadius: 10 },
  profileCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    marginBottom: 14,
  },
  profileName: { fontSize: 18, fontWeight: "700", marginTop: 8 },
  actionGroup: { borderWidth: 1, borderRadius: 14, marginBottom: 12 },
  actionRow: {
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#3f3f46",
  },
  roleBtn: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderBottomWidth: 0,
    padding: 16,
    maxHeight: "86%",
  },
  modalImage: { width: "100%", height: 220, borderRadius: 12 },
  closeBtn: { marginTop: 12, borderRadius: 10, paddingVertical: 12, alignItems: "center" },
  compareRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  compareBar: { flex: 1, height: 8, borderRadius: 99, overflow: "hidden" },
  compareFill: { height: "100%", borderRadius: 99 },
});
