import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  screenPad: { padding: 18, paddingBottom: 28 },
  hero: { borderWidth: 1, borderRadius: 24, padding: 18, marginBottom: 22, overflow: "hidden" },
  heroTitle: { fontSize: 30, fontWeight: "900", letterSpacing: 0.4 },
  sectionTitle: { fontSize: 22, fontWeight: "900", letterSpacing: 0.4 },
  sectionSubtitle: { marginTop: 5, fontSize: 12, textTransform: "uppercase", letterSpacing: 1.2 },
  screenTitle: { fontSize: 28, fontWeight: "900", marginBottom: 12, letterSpacing: 0.4 },
  card: { borderWidth: 1, borderRadius: 22, marginBottom: 16, overflow: "hidden" },
  cardImage: { width: "100%", height: 180 },
  cardBody: { padding: 14 },
  cardTitle: { fontSize: 18, fontWeight: "900", letterSpacing: 0.3 },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 10 },
  actionBtn: { borderRadius: 999, paddingVertical: 10, paddingHorizontal: 18 },
  actionBtnText: { color: "#1a120d", fontWeight: "900", letterSpacing: 0.3 },
  iconBtn: { borderWidth: 1, borderRadius: 999, width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  badge: {
    position: "absolute",
    left: 10,
    top: 10,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  badgeText: { color: "#f7efe2", fontSize: 10, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.8 },
  searchWrap: {
    borderWidth: 1,
    borderRadius: 18,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
  },
  searchInput: { flex: 1, paddingVertical: 12, paddingHorizontal: 8 },
  switchRow: { flexDirection: "row", alignItems: "center" },
  emptyWrap: {
    margin: 16,
    borderWidth: 1,
    borderRadius: 22,
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  stat: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginRight: 8,
    marginBottom: 10,
  },
  singleInput: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  listRow: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  thumb: { width: 64, height: 64, borderRadius: 10 },
  profileCard: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
    alignItems: "center",
    marginBottom: 14,
  },
  profileName: { fontSize: 18, fontWeight: "800", marginTop: 8, letterSpacing: 0.3 },
  actionGroup: { borderWidth: 1, borderRadius: 18, marginBottom: 12, overflow: "hidden" },
  actionRow: {
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#4a3727",
  },
  roleBtn: {
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "#0e0b09",
    justifyContent: "flex-end",
  },
  modalCard: {
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderBottomWidth: 0,
    padding: 18,
    maxHeight: "86%",
  },
  modalImage: { width: "100%", height: 220, borderRadius: 18 },
  closeBtn: { marginTop: 12, borderRadius: 999, paddingVertical: 13, alignItems: "center" },
  compareRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  compareBar: { flex: 1, height: 10, borderRadius: 99, overflow: "hidden" },
  compareFill: { height: "100%", borderRadius: 99 },
});
