import { StyleSheet } from "react-native";
import { fontFamilies, radii } from "./brand";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  screenPad: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 48 },
  scrollPad: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 96 },
  hero: { borderWidth: 1, borderRadius: radii.lg, padding: 18, marginBottom: 24, overflow: "hidden" },
  heroTitle: { fontSize: 40, lineHeight: 38, fontFamily: fontFamilies.headingBold, letterSpacing: -0.8, maxWidth: "72%" },
  heroCopy: { fontSize: 15, lineHeight: 24, fontFamily: fontFamilies.body },
  eyebrow: { fontSize: 12, textTransform: "uppercase", letterSpacing: 2.16, marginBottom: 10, fontFamily: fontFamilies.bodyBold },
  sectionTitle: { fontSize: 30, lineHeight: 30, fontFamily: fontFamilies.headingBold, letterSpacing: -0.6 },
  sectionSubtitle: { marginTop: 8, fontSize: 14, lineHeight: 22, fontFamily: fontFamilies.body },
  screenTitle: { fontSize: 36, lineHeight: 34, marginBottom: 12, letterSpacing: -0.8, fontFamily: fontFamilies.headingBold, maxWidth: "72%" },
  card: { borderWidth: 1, borderRadius: radii.md, marginBottom: 16, overflow: "hidden" },
  cardImage: { width: "100%", height: 220 },
  cardBody: { padding: 18 },
  cardTitle: { fontSize: 22, lineHeight: 22, fontFamily: fontFamilies.headingSemiBold, letterSpacing: -0.4 },
  bodyText: { fontSize: 15, lineHeight: 24, fontFamily: fontFamilies.body },
  metaText: { fontSize: 13, lineHeight: 18, fontFamily: fontFamilies.bodyMedium },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 14 },
  actionBtn: { borderRadius: 16, overflow: "hidden" },
  actionBtnInner: { minHeight: 48, paddingHorizontal: 18, paddingVertical: 12, alignItems: "center", justifyContent: "center" },
  actionBtnContent: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  actionBtnText: { color: "#241806", fontFamily: fontFamilies.bodyBold, fontSize: 15, letterSpacing: 0.2 },
  iconBtn: { borderWidth: 1, borderRadius: 16, width: 48, height: 48, alignItems: "center", justifyContent: "center" },
  ghostBtn: { minHeight: 48, borderWidth: 1, borderRadius: 16, alignItems: "center", justifyContent: "center", paddingHorizontal: 18, paddingVertical: 12 },
  ghostBtnText: { fontSize: 15, fontFamily: fontFamilies.bodyBold },
  badge: {
    position: "absolute",
    left: 12,
    top: 12,
    borderRadius: radii.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  badgeText: { color: "#F5F1E8", fontSize: 10, fontFamily: fontFamilies.bodyBold, textTransform: "uppercase", letterSpacing: 1.2 },
  searchWrap: {
    borderWidth: 1,
    borderRadius: radii.md,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    minHeight: 54,
  },
  searchInput: { flex: 1, paddingVertical: 12, paddingHorizontal: 10, fontSize: 15, fontFamily: fontFamilies.body },
  switchRow: { flexDirection: "row", alignItems: "center" },
  emptyWrap: {
    margin: 16,
    borderWidth: 1,
    borderRadius: radii.md,
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  stat: {
    flex: 1,
    borderWidth: 1,
    borderRadius: radii.md,
    padding: 14,
    marginRight: 8,
    marginBottom: 10,
  },
  singleInput: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 50,
    marginBottom: 8,
    fontSize: 15,
    fontFamily: fontFamilies.body,
  },
  inputLabel: { marginBottom: 6, fontSize: 13, fontFamily: fontFamilies.bodyMedium },
  inputError: { marginTop: 4, fontSize: 13, fontFamily: fontFamilies.bodyMedium },
  listRow: {
    borderWidth: 1,
    borderRadius: radii.md,
    padding: 12,
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
    marginBottom: 10,
  },
  thumb: { width: 92, height: 92, borderRadius: 18 },
  profileCard: {
    borderWidth: 1,
    borderRadius: radii.md,
    padding: 18,
    alignItems: "center",
    marginBottom: 14,
  },
  profileName: { fontSize: 22, lineHeight: 22, marginTop: 8, letterSpacing: -0.4, fontFamily: fontFamilies.headingSemiBold },
  actionGroup: { borderWidth: 1, borderRadius: radii.md, marginBottom: 12, overflow: "hidden" },
  actionRow: {
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  roleBtn: {
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(13, 11, 9, 0.7)",
    justifyContent: "flex-end",
  },
  modalCard: {
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
    borderWidth: 1,
    borderBottomWidth: 0,
    padding: 18,
    maxHeight: "86%",
  },
  modalHandle: { alignSelf: "center", width: 52, height: 5, borderRadius: radii.pill, marginBottom: 18 },
  modalImage: { width: "100%", height: 220, borderRadius: 18 },
  closeBtn: { marginTop: 12, borderRadius: 16, overflow: "hidden" },
  compareRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  compareBar: { flex: 1, height: 10, borderRadius: 99, overflow: "hidden" },
  compareFill: { height: "100%", borderRadius: 99 },
  statsGrid: { flexDirection: "row", gap: 12, marginTop: 18 },
  statLabel: { fontSize: 11, textTransform: "uppercase", letterSpacing: 1.2, fontFamily: fontFamilies.bodyBold },
  statValue: { marginTop: 6, fontSize: 24, lineHeight: 24, fontFamily: fontFamilies.headingBold },
  segmentedWrap: { borderRadius: radii.pill, borderWidth: 1, padding: 4, flexDirection: "row" },
  segmentedOption: { flex: 1, borderRadius: radii.pill, paddingVertical: 12, alignItems: "center", justifyContent: "center" },
  segmentedText: { fontSize: 14, fontFamily: fontFamilies.bodyBold },
  formCard: { borderWidth: 1, borderRadius: radii.md, padding: 18 },
});
